services:
  product-service:
    build:
      context: ./product-service/product-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=default

  inventory-service:
    build:
      context: ./inventory-service/inventory-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - backend
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8081
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - product-service

networks:
  backend:
